"""
Fetch todos from Notion and write docs/data.js for the GitHub Pages dashboard.
Reuses NotionClient from the desktop app.
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from notion_api import NotionClient


def main():
    token = os.environ.get("NOTION_TOKEN")
    if not token:
        print("NOTION_TOKEN environment variable not set")
        sys.exit(1)

    client = NotionClient(token)
    todos = client.collect_todos(recent_days=7)

    items = []
    for t in todos:
        items.append({
            "text": t["text"],
            "checked": t["checked"],
            "heading": t["heading"],
        })

    data = {
        "lastSynced": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "todos": items,
    }

    out_dir = Path(__file__).parent / "docs"
    out_dir.mkdir(exist_ok=True)

    with open(out_dir / "data.js", "w", encoding="utf-8") as f:
        f.write("// Auto-generated by sync_web.py — do not edit manually\n")
        f.write(f"const DATA = {json.dumps(data, indent=2)};\n")

    print(f"Wrote {len(items)} todos to docs/data.js")


if __name__ == "__main__":
    main()
